image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
  GIT_SSL_NO_VERIFY: "true"
  GIT_STRATEGY: "none"

before_script:
  - apk add --no-cache git docker-compose

stages:
  - build
  - deploy
  - migrate
  - test

build:
  stage: build
  script:
    - git clone https://glpat-Fjk-d7zg1vM--b8Sk_ys@10.0.6.30/proway/laravel-next.git --depth=1 .
    - docker compose build

deploy:
  stage: deploy
  script:
    - docker compose up -d

migrate:
  stage: migrate
  script:
    - docker exec laravel bash -c "bash seed.sh && bash import-csv.sh"

test:
  stage: test
  script:
    - docker exec laravel php artisan test