stages:
  - build
  - deploy
  - migrate
  - test

variables:
  GIT_SSL_NO_VERIFY: "true"
  GIT_STRATEGY: "none"

before_script:
  - apk add --no-cache git docker-cli docker-compose
  - nohup dockerd > /dev/null 2>&1 &
  - while ! docker info &>/dev/null; do sleep 1; done

build:
  stage: build
  script:
    - git clone https://glpat-Fjk-d7zg1vM--b8Sk_ys@10.0.6.30/proway/laravel-next.git --depth=1 .
    - docker compose build

deploy:
  stage: deploy
  script:
    - docker compose up -d

migrate:
  stage: migrate
  script:
    - docker exec -it laravel bash -c "bash seed.sh && bash import-csv.sh"

test:
  stage: test
  script:
    - docker exec -it laravel php artisan test
